Fix the etime() call
etime() is an intrinsic function, so it should not be declared "external",
otherwise one gets

    second.f:(.text+0x11): undefined reference to `etime_'

This patch fixes the problem.